version: '2'
services:
  mariadb:
    image: 'bitnami/mysql:8.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=bn_mediawiki
      - MYSQL_DATABASE=bitnami_mediawiki
    volumes:
      - 'mysql_data:/bitnami'
  mediawiki:
    build: .
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_PORT_NUMBER=3306
      - MYSQL_DATABASE_USER=bn_mediawiki
      - MYSQL_DATABASE_NAME=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:8181'
      - '443:8143'
    volumes:
      - 'mediawiki_data:/bitnami'
    depends_on:
      - mysqldb
volumes:
  mysql_data:
    driver: local
  mediawiki_data:
    driver: local
